### ISSUE TITLE
Split window does not open. Flashes

### ISSUE THREAD

**Issue by KasonBraley** [Alkindi42/tmux-bitwarden#1]
I am unable to get the window to open correctly after pressing the default bind key. The window flashes very quickly at the bottom of the tmux pane. Have you ran across this issue before?

**Comment by Alkindi42** [comment]
Do you have a message in your tmux status bar?

Are you sure you are logged in? https://github.com/Alkindi42/tmux-bitwarden#usage

**Comment by KasonBraley** [comment]
Yes I can confirm I am logged in. No message in the status bar, I do have the Nord tmux theme running. Not sure if that matters.

**Comment by Alkindi42** [comment]
I  tried with [Nord tmux theme](https://github.com/arcticicestudio/nord-tmux) but I had no problem. What is your tmux version? (I tested in tmux 3.0a). Do you have all the required binaries? (jq, bw and fzf)

**Comment by KasonBraley** [comment]
Tmux version is 3.2a. I've tried this on both my m1 Mac and my Intel Mac, and got the same result. All the required packages are installed. Here is a video showing the flashing (at the end). 

https://user-images.githubusercontent.com/59150626/122655859-bf0b5080-d10a-11eb-8d11-cb8db778fedd.mov

**Comment by Alkindi42** [comment]
Ok thanks for the details, can you try to run the script manually?

```bash
bash ~/.tmux/plugins/tmux-bitwarden/scripts/main.sh
```

**Comment by KasonBraley** [comment]
Yes it results in an error. 
`main.sh: line 32: @bw-session: syntax error: operand expected (error token is "@bw-session")`

If I `echo $BW_SESSION` I get my valid session token back correctly.

**Comment by Alkindi42** [comment]
What is your bash version?

**Comment by KasonBraley** [comment]
Bash version is 3.2, however I am using ZSH as my shell.

**Comment by Alkindi42** [comment]
That's the problem, is it mandatory for you to use an older version of bash? This should be better with bash> = 4.0

**Comment by KasonBraley** [comment]
Thank you that fixed the problem. Still had the default bash version installed on Mac. Updated to 5.1.8 and so far so good. Thank you for your help, looking forward to using this now.
