### ISSUE TITLE
session not used

### ISSUE THREAD

**Issue by xeTaiz** [Alkindi42/tmux-bitwarden#2]
Hey there,
thanks for the great plugin! This makes bw-cli a lot more usable.
However I am facing an issue and that is that the tmux extension keeps asking for my master password every time, despite setting the `BW_SESSION` env var.
I added both of these lines to my tmux.conf:
```
set -g @plugin 'Alkindi42/tmux-bitwarden'
set -g @bw-session 'BW_SESSION'
```
My env var is set and I need no re-authentication when using the bw cli directly (i.e. bw list items runs without asking for a pw)

Do you have an idea or maybe an easy entry to debug this myself, I'm not very familiar with tmux extensions and shell scripts tho.

**Comment by Alkindi42** [comment]
Hello,

> I added both of these lines to my tmux.conf:
> ```
> set -g @plugin 'Alkindi42/tmux-bitwarden'
> set -g @bw-session 'BW_SESSION'
> ```
Do we agree that in your example, "BW_SESSION" corresponds to the bitwarden secret? Did you have refresh your tmux configuration? 

> My env var is set and I need no re-authentication when using the bw cli directly (i.e. bw list items runs without asking for a pw)

What shell are you using?

**Comment by xeTaiz** [comment]
Hi, thanks for the response.
I figured that I had to put the actual secret in there yes, but after parsing through your scripts it makes no sense as the env var is used by default. I then found by adding some logs to your script, that the bw extension never has the BW_SESSION set.
The shell I'm using is fish.

**Comment by Alkindi42** [comment]
If you want to use the **BW_SESSION** var env, you need to add it system-wide or in your .bashrc. The tmux extension only loads bash variables.
In summary, you have two possibilities:
- set the secret in your tmux configuration `set -g @bw-session 'YOUR_SECRET'`
- set environment variable in your bashrc or system wide (/etc/environment, /etc/profile.d/*.sh, ...).

If you set your bitwarden secret in your tmux configuration **AND** in your environment variable, only the secret from the configuration file will be read. The env var is used by default only if you don't set the tmux **@bw-session** variable.
If you want to know the value of a tmux variable: `tmux show-option -gv "variable_name"`, for @bw-session: `tmux show-option -gv "@bw-session"`.

**Comment by xeTaiz** [comment]
Thanks a lot for your response, it helped me identify the issue :)
Also thanks again for making this public in the first place!

Closing then :)
